// src/constants/errorCodes.ts
export const ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE';
export const ACCOUNT_BANNED = 'ACCOUNT_BANNED';
export const ACCOUNT_DORMANT = 'ACCOUNT_DORMANT';
export const ACCOUNT_WITHDRAWN = 'ACCOUNT_WITHDRAWN';
export const UNKNOWN_ACCOUNT_STATUS = 'UNKNOWN_ACCOUNT_STATUS';
export const PASSWORD_EXPIRED = 'PASSWORD_EXPIRED';
export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const SUPABASE_LOGIN_UPDATE_FAILED = 'SUPABASE_LOGIN_UPDATE_FAILED';
export const MISSING_CREDENTIAL = 'MISSING_CREDENTIAL';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const USER_DATA_INCOMPLETE = 'USER_DATA_INCOMPLETE';
export const MISSING_FIELD = "MISSING_FIELD"
export const SUPABASE_DB_ERROR = "SUPABASE_DB_ERROR"
// 기타 필요한 공통 에러 코드
export const UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS';
export const INVALID_INPUT = 'INVALID_INPUT';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
